import { motion } from 'framer-motion';
import Link from 'next/link';
import GlassCard from '@/components/ui/GlassCard';
import { 
  FaWindows, FaApple, FaLinux, FaServer, FaCode, FaArrowRight, 
  FaGraduationCap, FaBook, FaLaptop, FaCloud, FaCogs
} from 'react-icons/fa';

export default function Home() {
  // Static Tailwind classes only — dynamic `border-${color}-500` names are
  // never generated by the JIT compiler, so map colors explicitly.
  const topicStyles: Record<string, { border: string; text: string }> = {
    blue: { border: 'border-blue-500', text: 'text-blue-500' },
    gray: { border: 'border-gray-500', text: 'text-gray-500' },
    orange: { border: 'border-orange-500', text: 'text-orange-500' },
    purple: { border: 'border-purple-500', text: 'text-purple-500' },
  };
  const timelineDot: Record<string, string> = {
    blue: 'bg-blue-500',
    gray: 'bg-gray-500',
    orange: 'bg-orange-500',
    purple: 'bg-purple-500',
  };
  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-8">
      {/* Hero Section */}
      <section className="relative overflow-hidden rounded-3xl glass p-8 md:p-12 border-2 border-primary/20">
        <div className="absolute -right-20 -top-20 w-64 h-64 bg-blue-500/10 rounded-full blur-3xl"></div>
        <div className="absolute -left-20 -bottom-20 w-64 h-64 bg-orange-500/10 rounded-full blur-3xl"></div>
        
        <motion.div
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.6 }}
          className="relative z-10 text-center"
        >
          <div className="flex items-center justify-center gap-6 mb-4">
            <FaWindows className="text-4xl text-blue-500" />
            <FaApple className="text-4xl text-gray-600 dark:text-gray-300" />
            <FaLinux className="text-4xl text-orange-500" />
          </div>
          
          <h1 className="text-4xl md:text-6xl font-extrabold leading-tight">
            <span className="text-blue-600">Windows</span>
            <span className="text-muted-foreground"> · </span>
            <span className="text-gray-600 dark:text-gray-300">macOS</span>
            <span className="text-muted-foreground"> · </span>
            <span className="text-orange-600">Linux</span>
            <br />
            <span className="text-primary">Academy</span>
          </h1>
          
          <p className="mt-4 text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto">
            Master operating systems, kernels, and backend engineering with interactive 
            lessons, diagrams, and quizzes.
          </p>
          
          <div className="mt-6 flex flex-wrap justify-center gap-4">
            <Link 
              href="/os" 
              className="px-6 py-3 bg-primary text-white rounded-full font-medium hover:bg-primary-dark transition shadow-lg hover:shadow-xl flex items-center gap-2"
            >
              <FaGraduationCap /> Start Learning
            </Link>
            <Link 
              href="/triple-comparison" 
              className="px-6 py-3 glass rounded-full font-medium hover:bg-white/30 dark:hover:bg-white/10 transition flex items-center gap-2"
            >
              <FaArrowRight /> Compare OS
            </Link>
          </div>
        </motion.div>
      </section>

      {/* Featured Topics */}
      <section>
        <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <FaBook className="text-primary" /> Featured Topics
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {[
            { icon: <FaWindows />, title: 'Windows', desc: 'NT Kernel, UI, and development', color: 'blue' },
            { icon: <FaApple />, title: 'macOS', desc: 'Unix-based, creative tools, Apple', color: 'gray' },
            { icon: <FaLinux />, title: 'Linux', desc: 'Open source, kernel, distros', color: 'orange' },
            { icon: <FaCogs />, title: 'Kernels', desc: 'Monolithic, Micro, Hybrid', color: 'purple' },
          ].map((topic, i) => (
            <GlassCard key={i} className={`text-center border-t-4 ${topicStyles[topic.color].border} hover:scale-105 transition`}>
              <div className={`text-3xl ${topicStyles[topic.color].text} mx-auto mb-2`}>{topic.icon}</div>
              <h3 className="text-lg font-semibold">{topic.title}</h3>
              <p className="text-sm text-muted-foreground">{topic.desc}</p>
            </GlassCard>
          ))}
        </div>
      </section>

      {/* OS Quick Comparison */}
      <section>
        <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <FaCogs className="text-primary" /> OS Quick Comparison
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <GlassCard className="text-center border-t-4 border-blue-500 hover:scale-105 transition">
            <FaWindows className="text-4xl text-blue-500 mx-auto mb-2" />
            <h3 className="text-lg font-bold text-blue-600">Windows</h3>
            <p className="text-xs text-muted-foreground">Best for Gaming & Business</p>
            <div className="mt-2 flex flex-wrap justify-center gap-1">
              <span className="px-2 py-0.5 bg-green-100 dark:bg-green-900/30 text-green-600 text-xs rounded-full">Gaming</span>
              <span className="px-2 py-0.5 bg-green-100 dark:bg-green-900/30 text-green-600 text-xs rounded-full">Office</span>
              <span className="px-2 py-0.5 bg-green-100 dark:bg-green-900/30 text-green-600 text-xs rounded-full">Software</span>
            </div>
          </GlassCard>

          <GlassCard className="text-center border-t-4 border-gray-500 hover:scale-105 transition">
            <FaApple className="text-4xl text-gray-600 dark:text-gray-300 mx-auto mb-2" />
            <h3 className="text-lg font-bold text-gray-600 dark:text-gray-300">macOS</h3>
            <p className="text-xs text-muted-foreground">Best for Creatives & Developers</p>
            <div className="mt-2 flex flex-wrap justify-center gap-1">
              <span className="px-2 py-0.5 bg-green-100 dark:bg-green-900/30 text-green-600 text-xs rounded-full">Design</span>
              <span className="px-2 py-0.5 bg-green-100 dark:bg-green-900/30 text-green-600 text-xs rounded-full">iOS Dev</span>
              <span className="px-2 py-0.5 bg-green-100 dark:bg-green-900/30 text-green-600 text-xs rounded-full">Music</span>
            </div>
          </GlassCard>

          <GlassCard className="text-center border-t-4 border-orange-500 hover:scale-105 transition">
            <FaLinux className="text-4xl text-orange-500 mx-auto mb-2" />
            <h3 className="text-lg font-bold text-orange-600">Linux</h3>
            <p className="text-xs text-muted-foreground">Best for Developers & Servers</p>
            <div className="mt-2 flex flex-wrap justify-center gap-1">
              <span className="px-2 py-0.5 bg-green-100 dark:bg-green-900/30 text-green-600 text-xs rounded-full">DevOps</span>
              <span className="px-2 py-0.5 bg-green-100 dark:bg-green-900/30 text-green-600 text-xs rounded-full">Cloud</span>
              <span className="px-2 py-0.5 bg-green-100 dark:bg-green-900/30 text-green-600 text-xs rounded-full">Security</span>
            </div>
          </GlassCard>
        </div>
      </section>

      {/* History Timeline */}
      <section>
        <h2 className="text-2xl font-bold mb-4">📜 History Timeline</h2>
        <GlassCard>
          <div className="relative flex flex-col gap-3 before:absolute before:left-4 before:top-0 before:h-full before:w-1 before:bg-primary/30">
            {[
              { year: 1984, title: 'Macintosh (System 1)', color: 'gray' },
              { year: 1985, title: 'Windows 1.0', color: 'blue' },
              { year: 1991, title: 'Linux Kernel released', color: 'orange' },
              { year: 1993, title: 'Debian', color: 'orange' },
              { year: 1994, title: 'Linux 1.0', color: 'orange' },
              { year: 1995, title: 'Windows 95', color: 'blue' },
              { year: 2001, title: 'Windows XP', color: 'blue' },
              { year: 2001, title: 'Mac OS X', color: 'gray' },
              { year: 2003, title: 'Windows Server', color: 'blue' },
              { year: 2016, title: 'Windows Subsystem for Linux', color: 'purple' },
              { year: 2020, title: 'Apple Silicon (M1)', color: 'gray' },
              { year: 2026, title: 'Linux dominates cloud', color: 'orange' },
            ].map((event, i) => (
              <motion.div
                key={i}
                initial={{ x: -20, opacity: 0 }}
                animate={{ x: 0, opacity: 1 }}
                transition={{ delay: i * 0.06 }}
                className="flex items-center gap-4 ml-12 relative"
              >
                <div className={`absolute -left-10 w-5 h-5 rounded-full border-4 border-white dark:border-slate-800 ${timelineDot[event.color]}`}></div>
                <span className="text-lg font-mono font-bold text-primary min-w-[60px]">{event.year}</span>
                <span className="text-sm">{event.title}</span>
              </motion.div>
            ))}
          </div>
        </GlassCard>
      </section>

      {/* Learning Roadmap */}
      <section>
        <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <FaLaptop className="text-primary" /> Learning Roadmap
        </h2>
        <GlassCard className="border-2 border-primary/20">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {[
              'Programming Fundamentals',
              'JavaScript & Node.js',
              'Express & REST API',
              'PostgreSQL & JWT',
              'Linux & Docker',
              'NGINX & Cloud'
            ].map((step, i) => (
              <div key={i} className="flex items-center gap-3 p-3 hover:bg-primary/5 rounded-lg transition border border-white/10">
                <span className="flex items-center justify-center w-8 h-8 rounded-full bg-primary text-white text-sm font-bold">
                  {i + 1}
                </span>
                <span className="text-sm">{step}</span>
              </div>
            ))}
          </div>
          <div className="mt-4 text-center">
            <Link 
              href="/roadmap" 
              className="text-primary hover:underline font-medium inline-flex items-center gap-1"
            >
              View Full Roadmap <FaArrowRight className="text-sm" />
            </Link>
          </div>
        </GlassCard>
      </section>

      {/* Quick Links */}
      <section>
        <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
          <FaCloud className="text-primary" /> Quick Start
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3">
          {[
            { href: '/os-overview', label: 'OS Overview', icon: '📚' },
            { href: '/evolution', label: 'Evolution', icon: '📜' },
            { href: '/triple-comparison', label: 'OS Comparison', icon: '📊' },
            { href: '/commands', label: 'Commands', icon: '💻' },
          ].map((item, i) => (
            <Link key={i} href={item.href}>
              <GlassCard className="text-center hover:scale-105 transition hover:border-primary/50 border border-white/10">
                <div className="text-3xl mb-1">{item.icon}</div>
                <p className="font-medium text-sm">{item.label}</p>
              </GlassCard>
            </Link>
          ))}
        </div>
      </section>

      {/* Call to Action */}
      <GlassCard className="bg-gradient-to-r from-blue-50 via-gray-50 to-orange-50 dark:from-blue-950/20 dark:via-gray-950/20 dark:to-orange-950/20 border-2 border-primary/20 text-center">
        <div className="flex justify-center gap-6 text-3xl mb-3">
          <FaWindows className="text-blue-500" />
          <FaApple className="text-gray-600 dark:text-gray-300" />
          <FaLinux className="text-orange-500" />
        </div>
        <h2 className="text-2xl font-bold mb-2">Ready to Start Learning?</h2>
        <p className="text-muted-foreground max-w-2xl mx-auto">
          Explore our comprehensive lessons on Windows, macOS, Linux, kernels, and backend development.
        </p>
        <div className="mt-4 flex flex-wrap justify-center gap-4">
          <Link 
            href="/os" 
            className="px-6 py-2 bg-primary text-white rounded-full hover:bg-primary-dark transition"
          >
            Get Started
          </Link>
          <Link 
            href="/quiz" 
            className="px-6 py-2 glass rounded-full hover:bg-white/30 dark:hover:bg-white/10 transition"
          >
            Take a Quiz
          </Link>
        </div>
      </GlassCard>
    </motion.div>
  );
}
